# Generated by Django 4.1.3 on 2022-12-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0002_alter_platos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platos',
            name='precio',
            field=models.IntegerField(max_length=10),
        ),
    ]
