# Generated by Django 4.1.3 on 2022-12-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0003_alter_platos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='pais',
            field=models.CharField(default='', max_length=25),
        ),
    ]
