# Generated by Django 4.1.3 on 2022-11-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_menu', models.CharField(max_length=40)),
                ('lista', models.CharField(max_length=20)),
                ('ingredientes', models.CharField(max_length=12)),
            ],
        ),
    ]
